/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MotorcycleLessonsAshkelonRouteImport } from './routes/motorcycle-lessons-ashkelon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CarLessonsAshkelonRouteImport } from './routes/car-lessons-ashkelon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLicenseCardsRouteImport } from './routes/admin.license-cards'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLandingPagesRouteImport } from './routes/admin.landing-pages'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorcycleLessonsAshkelonRoute =
  MotorcycleLessonsAshkelonRouteImport.update({
    id: '/motorcycle-lessons-ashkelon',
    path: '/motorcycle-lessons-ashkelon',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CarLessonsAshkelonRoute = CarLessonsAshkelonRouteImport.update({
  id: '/car-lessons-ashkelon',
  path: '/car-lessons-ashkelon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicenseCardsRoute = AdminLicenseCardsRouteImport.update({
  id: '/license-cards',
  path: '/license-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/car-lessons-ashkelon': typeof CarLessonsAshkelonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motorcycle-lessons-ashkelon': typeof MotorcycleLessonsAshkelonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/license-cards': typeof AdminLicenseCardsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/car-lessons-ashkelon': typeof CarLessonsAshkelonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motorcycle-lessons-ashkelon': typeof MotorcycleLessonsAshkelonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/license-cards': typeof AdminLicenseCardsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/car-lessons-ashkelon': typeof CarLessonsAshkelonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motorcycle-lessons-ashkelon': typeof MotorcycleLessonsAshkelonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/license-cards': typeof AdminLicenseCardsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/car-lessons-ashkelon'
    | '/dashboard'
    | '/login'
    | '/motorcycle-lessons-ashkelon'
    | '/sitemap.xml'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/landing-pages'
    | '/admin/leads'
    | '/admin/license-cards'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/'
    | '/api/public/lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/car-lessons-ashkelon'
    | '/dashboard'
    | '/login'
    | '/motorcycle-lessons-ashkelon'
    | '/sitemap.xml'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/landing-pages'
    | '/admin/leads'
    | '/admin/license-cards'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin'
    | '/api/public/lead'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/car-lessons-ashkelon'
    | '/dashboard'
    | '/login'
    | '/motorcycle-lessons-ashkelon'
    | '/sitemap.xml'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/landing-pages'
    | '/admin/leads'
    | '/admin/license-cards'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/'
    | '/api/public/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarLessonsAshkelonRoute: typeof CarLessonsAshkelonRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MotorcycleLessonsAshkelonRoute: typeof MotorcycleLessonsAshkelonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorcycle-lessons-ashkelon': {
      id: '/motorcycle-lessons-ashkelon'
      path: '/motorcycle-lessons-ashkelon'
      fullPath: '/motorcycle-lessons-ashkelon'
      preLoaderRoute: typeof MotorcycleLessonsAshkelonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-lessons-ashkelon': {
      id: '/car-lessons-ashkelon'
      path: '/car-lessons-ashkelon'
      fullPath: '/car-lessons-ashkelon'
      preLoaderRoute: typeof CarLessonsAshkelonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/license-cards': {
      id: '/admin/license-cards'
      path: '/license-cards'
      fullPath: '/admin/license-cards'
      preLoaderRoute: typeof AdminLicenseCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLicenseCardsRoute: typeof AdminLicenseCardsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminErrorsRoute: AdminErrorsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLicenseCardsRoute: AdminLicenseCardsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarLessonsAshkelonRoute: CarLessonsAshkelonRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MotorcycleLessonsAshkelonRoute: MotorcycleLessonsAshkelonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
